# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from example import application_pb2 as example_dot_application__pb2


class UserMortgageServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Check = channel.unary_unary(
        '/UserMortgageService/Check',
        request_serializer=example_dot_application__pb2.SimpleMessage.SerializeToString,
        response_deserializer=example_dot_application__pb2.SimpleMessage.FromString,
        )
    self.Check2 = channel.unary_unary(
        '/UserMortgageService/Check2',
        request_serializer=example_dot_application__pb2.SimpleMessage.SerializeToString,
        response_deserializer=example_dot_application__pb2.SimpleMessage.FromString,
        )


class UserMortgageServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Check(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Check2(self, request, context):
    """asd asd
    WAWSdasDWDASWDaD sad asd
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UserMortgageServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Check': grpc.unary_unary_rpc_method_handler(
          servicer.Check,
          request_deserializer=example_dot_application__pb2.SimpleMessage.FromString,
          response_serializer=example_dot_application__pb2.SimpleMessage.SerializeToString,
      ),
      'Check2': grpc.unary_unary_rpc_method_handler(
          servicer.Check2,
          request_deserializer=example_dot_application__pb2.SimpleMessage.FromString,
          response_serializer=example_dot_application__pb2.SimpleMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'UserMortgageService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
